# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Réseau IABM
email: reseauiabm@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Chercheurs français en Intelligence Artificielle appliquée à l'Imagerie Biomédicale.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  reseau-iabm

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme

collections:
  labos:
    output: true

defaults:
  - scope:
      path: ""
      type: labos
    values:
      layout: labo

# Theme
remote_theme: "jeffreytse/jekyll-theme-yat@v1.10.0"

header_transparent: false
lang: "fr"
night_mode: "on/off"

banner:
  opacity: 0.3            # Banner opacity (100% is 1.0)

header_pages:
  - about.md
  - archives.md
  - contact.md
  - contribute.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
